extract = 'total_dyn_inst: (\d+)'
benchmarks = 'benchmarks/*/*.bril'
timeout = 15

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.garbage_collected]
pipeline = [
    "bril2json",
    "brili-gc -p {args}",
]
