extract = 'total_dyn_inst: (\d+)'
benchmarks = 'benchmarks/*/*.bril'
timeout = 15

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.to_ssa]
pipeline = [
    "bril2json",
    "./l6_ssa",
    "brili -p {args}",
]